# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
