# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_especie_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
