# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_auto_20170827_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='clasificacionTax',
            field=models.CharField(max_length=500),
        ),
    ]
