# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_auto_20170827_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nombreCientifico',
            field=models.CharField(max_length=300),
        ),
    ]
